# Generated by Django 4.2.8 on 2024-01-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
