# Generated by Django 4.2.8 on 2024-01-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
