# Generated by Django 4.2.8 on 2024-01-13 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.CharField(choices=[(1, 'High'), (2, 'Low')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
    ]
